/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "login": [],
    "register": [],
    "register.store": [],
    "logout": [],
    "dashboard": [],
    "products.index": [],
    "products.create": [],
    "products.store": [],
    "products.show": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "products.edit": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "products.update": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "products.destroy": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
